#!/usr/bin/env bash

# Exit on Failure
set -e

# Get base project directory and dotfiles directory
local base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
local dotfile_dir="${HOME}/.dotfiles"

# Make sure it's in the right location
if [[ ! -e ${dotfile_dir} ]]; then
  mv ${base_dir} ${dotfile_dir}
elif [[ ${base_dir} != ${dotfile_dir} ]]; then
  echo >&2 "ERROR: A dotfiles directory already exists."
  echo >&2 "Please remove ${dotfile_dir} before continuing."
  exit 1
fi

# Update submodules
cd "${dotfile_dir}"
git submodule update --init --recursive

if [[ command -v rcup >/dev/null 2>&1 ]]; then
  echo >&2 "ERROR: RCM must be installed to complete installation."
  echo >&2 "Follow instructions linked below and re-run the installation file:"
  echo >&2 "  https://github.com/thoughtbot/rcm#installation"
  exit 1
else
  env RCRC=${dotfile_dir}/rcrc rcup
fi
