#!/usr/bin/env bash

set -e

CONFIG="uninstall.conf.yaml"
DOTBOT_DIR="dotbot"
PLUGIN_FILE="uninstall.py"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" --plugin "${PLUGIN_FILE}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
