#!/usr/bin/env zsh

dotfile_dir="${HOME}/.dotfiles"

if [[ ! -d ${dotfile_dir} ]]; then
  echo >&2 "ERROR: Directory \"${dotfile_dir}\" could not be found."
  exit 1
fi

git --git-dir ${dotfile_dir}/.git --work-tree ${dotfile_dir} pull origin master
git --git-dir ${dotfile_dir}/.git --work-tree ${dotfile_dir} submodule update --recursive --remote --init
rcup
