[settings]
activate_aggressive = true
go_set_gobin = false
idiomatic_version_file_enable_tools = ["node", "python"]

[env]
MISE_DEFAULT_CONFIG_FILENAME = ".mise.local.toml"

[alias]
bash-language-server = "npm:bash-language-server"
docker-language-server = "github:docker/docker-language-server"
gopls = "go:golang.org/x/tools/gopls"
intelephense = "npm:intelephense"
language-server = "npm:@vtsls/language-server"
markdownlint-cli = "npm:markdownlint-cli"
neovim = "github:neovim/neovim" # enables nightly installs
prettierd = "npm:@fsouza/prettierd"
pyright = "npm:pyright"
solargraph = "gem:solargraph"
stylelint = "npm:stylelint"
tinymist = "github:myriad-dreamin/tinymist"
vscode-langservers-extracted = "npm:vscode-langservers-extracted"
yaml-language-server = "npm:yaml-language-server"

[tools]
fzf = "latest"
go = "latest"
neovim = "latest"
node = "lts"
nomad = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
tree-sitter = "latest"
uv = "latest"

bash-language-server = "latest"
biome = "latest"
docker-language-server = "latest"
golangci-lint = "latest"
gopls = "latest"
hadolint = "latest"
intelephense = "latest"
language-server = "latest"
lua-language-server = "latest"
markdownlint-cli = "latest"
prettierd = "latest"
pyright = "latest"
ruff = "latest"
rust-analyzer = "latest"
shellcheck = "latest"
shfmt = "latest"
solargraph = "latest"
stylelint = "latest"
stylua = "latest"
tinymist = "latest"
vscode-langservers-extracted = "latest"
yaml-language-server = "latest"
yamllint = "latest"
