#!/usr/bin/env fish
for cmd in dotbot mise
    if ! command -q $cmd
        echo "$cmd is required for installation" >&2
        exit 1
    end
end

SHELL=fish dotbot -c install.conf.yaml
mise install
